name: Deployment pipeline

on:
  push:
    branches:
      - master

jobs:
  lint-and-test:
    name: Lint and test
    runs-on: ubuntu-latest
    container: node:22-bookworm-slim
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          # Allow connecting with URI only
          POSTGRES_HOST_AUTH_METHOD: trust
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm run installDependenciesDev
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run testBackend
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    needs: [lint-and-test]
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Install dependencies
        run: npm run installDependenciesDev
      - name: Build app
        run: npm run build
      - name: Deploy
        run: fly deploy --remote-only --ha=false
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
